### ISSUE TITLE
As a user, I want to add Memes.

### ISSUE THREAD

**Issue by bel90** [cihantas/SocialNetwork#1]
- Uploading a Meme
- Set title (maybe a description?)
For next sprint:
- Set Hashtags
- Set visibility (special Groups, or all)

**Comment by cihantas** [comment]
Auf den ersten Blick sind folgende Punkte der Laravel Dokumentation für die Erfüllung dieser Aufgabe relevant:

- [Routing - Wie verbinde ich eine URL mit einer Controllermethode?](https://laravel.com/docs/5.4/routing)

- [CSRF Protection](https://laravel.com/docs/5.4/csrf) ist ein Feld in jedem Formular, dass eine bestimmte Sicherheitslücke schliesst. **Ohne dieses Feld wird beim Absenden eines Formulars immer ein Fehler geworfen.**

- [Controller - Was soll beim Aufruf der URL geschehen?](https://laravel.com/docs/5.4/controllers)

- [Views](https://laravel.com/docs/5.4/views) und [Templates](https://laravel.com/docs/5.4/blade) sind sozusagen HTML mit optionalen Platzhaltern. Das was der User also am Ende tatsächlich im Browser sieht z.B. dein Formular zum Posten.

- [Filesystem - Um Dateien hochzuladen](https://laravel.com/docs/5.4/filesystem)

- [Database Eloquent - Wie speichere ich das Meme in der Datenbank?](https://laravel.com/docs/5.4/eloquent)

Ich empfehle als erstes einen entsprechenden MemeController zu erstellen. Dann verbindest du den Controller mit einer URL über die eine Methode dann aufgerufen wird. Diese Methode soll dann eine View an den User schicken. Diese View soll das Uploadformular enthalten. 

Ist nicht viel, wird aber für den Anfang sicher nicht einfach. Falls du Probleme hast, kommentiere hier oder schreib mich im Slack an.

**Comment by bel90** [comment]
Ich habe nun einen neuen view newmeme.blade.php erstellt, der unter /newmeme mit get erreichbar ist. Post habe ich auch versucht zu implementieren, jedoch bekomme ich zur Zeit noch einen "No such table" Fehler in meinem MemeController. Ich konnte aber leider nicht herausfinden wieso die Datenbank nicht gefunden wird. 
Bisher versuche ich nur den Titel in der Datenbank zu speichern. Sobald das klappt wollte ich den Rest hinzufügen.
Das Bild habe ich bereits im public-Ordner versucht abzuspeichern (storage/app/public/memes), aber dabei wird lediglich der Bildname in einer Datei gespeichert.
Meine aktuelle Version habe ich in meinem Git hochgeladen: [https://github.com/bel90/SocialNetwork](url)

**Comment by bel90** [comment]
Habe nun eine neue Version in meinem Fork hochgeladen.

Erklärung zur aktuellen Funktionsweise:
Unter /newmeme kann man nun ein neues Meme der Datenbank hinzufügen (davor in der vagrant Konsole "php artisan migrate" machen, damit die neue Meme-Datenbank nutzbar  ist). Danach wird man wieder auf die Startseite weitergeleitet. In Zukunft soll hier das neu erstellte Meme angezeigt werden.
Unter /show_all wird eine Liste der Titel aller Memes angezeigt. Die Seite habe ich zu Testzwecken erstellt um zu sehen ob auch wirklich in der Datenbank gespeichert wurde. Die Seite kann nach belieben erweitert werden.

Aktuelle Probleme:
Die Bilder werden leider immer noch nicht ordentlich gespeichert. Wie in meinem letzten Kommentar wird der Titel des hochzuladenden Bildes in einer Datei in storage/app/public/memes gespeichert. Ich habe verschiedene Sachen ausprobiert die alle nicht funktioniert haben. Versuche ich auf das Bild mit $request->file('picture') zuzugreifen bekomme ich einen NULL Fehler. Mir scheint es momentan so, dass das Bild nicht ordentlich hochgeladen wird und nicht zur Verarbeitung zur Verfügung steht. Ich wäre sehr glücklich darüber wenn jemand weiß oder herausfindet wo der Fehler liegt.

**Comment by bel90** [comment]
Aufgabe ist soweit in meinem Fork erledigt.
Zur aktuellen Funktionsweise:
- /newmeme : Formular um neue Memes hinzuzufügen. Nach dem hinzufügen wird das Meme angezeigt.
- /show_all : Testseite. Hauptsächlich um zu sehen welche Einträge in der Datenbank vorhanden sind. Kann gerne nach belieben geändert werden.
- /show_meme/{id} : Zeigt das Meme mit der gegebenen ID an.

Damit die neue Datenbank funktioniert daran denken in der vagrant Konsole einmal "php artisan migrate" auszuführen.

**Comment by TOWTsi** [comment]
Hallo zusammen!
Ich habe bei mir im Ordner den Fork von Belinda übernommen und die Funktion eingebaut, dass man Hashtags setzen kann und diese automatisch in Relation zu den Memes stehen. Somit kann man bei mir die aktuellere Variante der Memeerstellung finden. Neue Seiten die hinzugekommen sind:

* /show_all_tags: Zeigt alle bestehenden Hashtags an. Dopplungen sind abgefangen und kommen nicht vor.
* /show_all_tag_relations: Zeigt alle Relationen die derzeit bestehen an.

Zudem habe ich mal die README.md geändert, damit man hier vorfindet, wie man den Code nach den Clonen in die lokale Umgebung wieder zum laufen bekommt.
