### ISSUE TITLE
As a user I want to edit my comment 

### ISSUE THREAD

**Issue by ezgiadas** [cihantas/SocialNetwork#42]

**Comment by cihantas** [comment]
Ich denke es waere einfacher, wenn mein sein Kommentar einfach loeschen kann und ein neues schreiben kann. Wir sparen uns am Anfang damit etwas arbeit und koennten das Feature spaeter noch hinzufuegen.

Weil man das editieren von Kommentaren manchmal ein wenig ausnutzen kann. Wuerde ich Montag nochmal drauf eingehen.
